### ISSUE TITLE
Question about the absence of chamfer_3D

### ISSUE THREAD

**Issue by DDgogogo** [DiT-3D/DiT-3D#11]
When I run test.py, I get the following error, can you tell me how to fix it. 
```
(base) root@ubuntu1804:~/DiT-3D# python test.py --dataroot data/ShapeNetCore.v2.PC15k/     --category chair     --model_type 'DiT-S/4'     --voxel_size 32     --model checkpoint/checkpoint.pth
Jitting Chamfer 3D
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from metrics.evaluation_metrics import jsd_between_point_cloud_sets as JSD
  File "/root/DiT-3D/metrics/evaluation_metrics.py", line 9, in <module>
    from metrics.ChamferDistancePytorch.chamfer3D.dist_chamfer_3D import chamfer_3DDist
  File "/root/DiT-3D/metrics/ChamferDistancePytorch/chamfer3D/dist_chamfer_3D.py", line 12, in <module>
    chamfer_3D = load(name="chamfer_3D",
  File "/home/vipuser/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 986, in load
    return _jit_compile(
  File "/home/vipuser/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1213, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/vipuser/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1560, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/vipuser/miniconda3/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'chamfer_3D'

```

**Comment by DDgogogo** [comment]
I was able to run test_emd_loss.py and the compile step I think was successful
```
 (base) root@ubuntu1804:~/DiT-3D/metrics/PyTorchEMD# python test_emd_loss.py 
 tensor([[ 1.7000, -0.1000 , 0.1000],
```

**Comment by DiT-3D** [comment]
Please try to follow README and set up the environment properly.

**Comment by hy-yhson** [comment]
@DDgogogo 
Hello, I encountered the same problem. 
Did you resolve it successfully?
