### ISSUE TITLE
Error in test.py

### ISSUE THREAD

**Issue by sIHURs** [DiT-3D/DiT-3D#19]
hi, 

I encountered the following error while running `test.py`, indicating that a tensor is not on the same device. I couldn't locate where set wrong for this issue. Both the data and the model should be on the GPU, (I have only one GPU). I didn't make any changes to the `class gaussiandiffusion` and `class model`.

```bash
Traceback (most recent call last):
  File "/home/yifan/studium/3D_Completion/DiT-3D_2024AILab/test.py", line 647, in <module>
    main(opt)
  File "/home/yifan/studium/3D_Completion/DiT-3D_2024AILab/test.py", line 493, in main
    test(opt.gpu, opt, output_dir)
  File "/home/yifan/studium/3D_Completion/DiT-3D_2024AILab/test.py", line 571, in test
    stats = generate_eval(model, opt, gpu, outf_syn, evaluator)
  File "/home/yifan/studium/3D_Completion/DiT-3D_2024AILab/test.py", line 444, in generate_eval
    gen = model.gen_samples(x.shape, gpu, new_y_chain(gpu,y.shape[0],opt.num_classes), clip_denoised=False).detach().cpu()
  File "/home/yifan/studium/3D_Completion/DiT-3D_2024AILab/test.py", line 291, in gen_samples
    return self.diffusion.p_sample_loop(self._denoise, shape=shape, device=device, y=y, noise_fn=noise_fn,
  File "/home/yifan/studium/3D_Completion/DiT-3D_2024AILab/test.py", line 219, in p_sample_loop
    img_t = self.p_sample(denoise_fn=denoise_fn, data=img_t,t=t_, noise_fn=noise_fn, y=y,
  File "/home/yifan/studium/3D_Completion/DiT-3D_2024AILab/test.py", line 195, in p_sample
    model_mean, _, model_log_variance, pred_xstart = self.p_mean_variance(denoise_fn, data=data, t=t, y=y, clip_denoised=clip_denoised,
  File "/home/yifan/studium/3D_Completion/DiT-3D_2024AILab/test.py", line 165, in p_mean_variance
    x_recon = self._predict_xstart_from_eps(data, t=t, eps=model_output)
  File "/home/yifan/studium/3D_Completion/DiT-3D_2024AILab/test.py", line 186, in _predict_xstart_from_eps
    self._extract(self.sqrt_recipm1_alphas_cumprod.to(x_t.device), t, x_t.shape) * eps
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

i used script:
```bash
python test.py --dataroot /home/yifan/studium/3D_Completion/DiT-3D_2024AILab/datasets/data/ShapeNetCore.v2.PC15k/ \
    --category chair --num_classes 1 \
    --bs 64 \
    --model_type 'DiT-S/4' \
    --voxel_size 32 \
    --model /home/yifan/studium/3D_Completion/DiT-3D_2024AILab/checkpoints/checkpoint.pth
```

What could be causing this error? 
Thank you very much.

yifan

**Comment by gaoalexander** [comment]
Was this solved?  I'm experiencing the same issue.

**Comment by sIHURs** [comment]
> Was this solved? I'm experiencing the same issue.

I don’t remember very clearly. The issue might be that I only have one GPU and didn’t set the GPU number correctly, such as 0. 
```bash
--gpu 0
```
